### ISSUE TITLE
Dockerの軽量化

### ISSUE THREAD

**Issue by H0R15H0** [randombar164/ouchi_bar#110]
重すぎて開発体験が悪いのでなんとかする

とりあえずnode_modulesのマウントはやめよう。

**Comment by YutaK1026** [comment]
node_modulesをdockerignoreしてやりたい

**Comment by H0R15H0** [comment]
多分Webpackの設定次第で動作は軽くなるはず。
以前のかわちゃんのプルリクの中で`watchOption`を外したのでそれだけでもちょっとは軽くなりそうだけど。。。
@Hide-nu 具体的にどこが重いか書いておいてもらえると原因究明できる気がします！

例：
- そもそもAttachが重い
- フロントエンドコンパイル遅い

あと、`docker-compose up`の動画取っておいてもらえると助かるかも
