### ISSUE TITLE
データの移行スクリプトを書く

### ISSUE THREAD

**Issue by H0R15H0** [randombar164/ouchi_bar#91]
旧データベース：https://dbdiagram.io/d/5eb7f19539d18f5553fef76f
新データベース：https://dbdiagram.io/d/5eb9fbda39d18f5553ff0c4c

データベース構造の変更に伴ってデータの移行スクリプトを自走したい。

# 求める形式
新データベースに沿った（二次元）配列に格納して欲しい。（全テーブル）

**Comment by YutaK1026** [comment]
## テーブル名の変更点
| 前 | 後|
----|----
| concrete_ingredients_handling_stores | ingredients_handling_stores |
| concrete_ingredients | ingredients |
| cocktails_concrete_ingredients | cocktails_ingredients |
| 追加 | amazon_browse_node |

## カラム名の変更点
| テーブル名 | 前 | 後 |
----|----|----
| concrete_ingredients_handling_stores | concrete_ingredient_id | ingredient_id |
| concrete_ingredients | base_ingredient_id | 削除 |
| concrete_ingredients | tag | 削除 | 
| cocktails_concrete_ingredients | concrete_ingredient_id | ingredient_id |
| cocktails_concrete_ingredients | 追加 | allow_category |
| categories | category_full_path | full_path |
| categories | percent_category_id | 削除 |

**Comment by YutaK1026** [comment]
## カラムの網羅

### handling_store
| 前 | 後 |
----|----
| handling_stores.id | handling_stores.id |
| handling_stores.name | handling_stores.name |
| handling_stores.created_at | handling_stores.created_at |
| handling_stores.updated_at | handling_stores.updated_at |

### ingredients_handling_stores
| 前 | 後 |
----|----
| concrete_ingredients_handling_stores.id | ingredients_handling_stores.id |
| concrete_ingredients_handling_stores.concrete_ingredient_id | ingredients_handling_stores.ingredient_id |
| concrete_ingredients_handling_stores.handling_store_id | ingredients_handling_stores.handling_store_id |
| concrete_ingredients_handling_stores.created_at | ingredients_handling_stores.created_at |
| concrete_ingredients_handling_stores.updated_at | ingredients_handling_stores.updated_at |

### ingredients
| 前 | 後 |
----|----
| concrete_ingredients.id | ingredients.id |
| concrete_ingredients.base_ingredient_id | ingredients.category_id |
| concrete_ingredients.name | ingredients.name |
| concrete_ingredients.tag | ingredients.created_at |
| concrete_ingredients.created_at | ingredients.updated_at |
| concrete_ingredients.updated_at | ingredients.img_src |
| concrete_ingredients.img_src | ingredients.jan_code |
| concrete_ingredients.category_id | ingredients.asin |
| concrete_ingredients.jan_code | ingredients.detail_page_url |
| concrete_ingredients.asin | ingredients.registerd_by_user |
| concrete_ingredients.detail_page_url | |
| concrete_ingredients.registerd_by_user | |

### amazon_browse_nodes
| 前 | 後 |
----|----
| | amazon_browse_nodes.id |
| | amazon_browse_nodes.amazon_browse_node_id |
| | amazon_browse_nodes.name |
| | amazon_browse_nodes.node_path |

### categories
| 前 | 後 |
----|----
| categories.id | categories.id |
| categories.name | categories.name |
| categories.amazon_browse_node_id | categories.full_path |
| categories.category_full_path | categories.amazon_browse_node_id |
| categories.parent_category_id | cateogries.created_at |
| categories.created_at | categories.updated_at | 
| categories.updated_at | |

### cocktails_ingredients
| 前 | 後 |
----|----
| cocktails_concrete_ingredients.id | cocktails_ingredients.id |
| cocktails_concrete_ingredients.concrete_ingredient_id | cocktails_ingredients.ingredient_id |
| cocktails_concrete_ingredients.cocktail_id | cocktails_ingredients.allow_category | 
| cocktails_concrete_ingredients.amount | cocktails_ingredients.cocktail_id |
| cocktails_concrete_ingredients.additional_explanation | cocktails_ingredients.amount | 
| cocktails_concrete_ingredients.unit_id | cocktails_ingredients.additional_explanation |
| cocktails_concrete_ingredients.created_at | cocktails_ingredients.unit_id |
| cocktails_concrete_ingredients.updated_at | cocktails_ingredients.created_at |
| | cocktails_ingredients.updated_at |

### cocktails
| 前 | 後 |
----|----
| cocktails.id | cocktails.id |
| cocktails.name | cocktails.name |
| cocktails.strength | cocktails.strength | 
| cocktails.cook_explanation | cocktails.cook_explanation |
| cocktails.drink_method_id | cocktails.drink_method_id |
| cocktails.glass_type_id | cocktails.glass_type_id |
| cocktails.created_at | cocktails.created_at |
| cocktails.updated_at | cocktails.updated_at |

### drink_methods
| 前 | 後 |
----|----
| drink_methods.id | drink_methods.id |
| drink_methods.name | drink_methods.name |
| drink_methods.created_at | drink_methods.created_at |
| drink_methods.updated_at | drink_methods.updated_at |

### glass_types
| 前 | 後 |
----|----
| glass_types.id | glass_types.id |
| glass_types.name | glass_types.name |
| glass_types.created_at | glass_types.created_at |
| glass_types.updated_at | glass_types.updated_at |

### units
| 前 | 後 |
----|----
| units.id | units.id |
| units.name | units.name |
| units.created_at | units.created_at |
| units.updated_at | units.updated_at |

### unit_conversions
| 前 | 後 |
----|----
| unit_conversions.id | unit_conversions.id |
| unit_conversions.unit_id | unit_conversions.unit_id |
| unit_conversions.amount | unit_conversions.amount |
| unit_conversions.created_at | unit_conversions.created_at |
| unit_conversions.updated_at | unit_conversions.updated_at |
